export enum UserRole {
  RECEPTIONIST = 'RECEPTIONIST',
  MEDTECH = 'MEDTECH',
  SUPERVISOR = 'SUPERVISOR',
  PHYSICIAN = 'PHYSICIAN',
  PATIENT = 'PATIENT',
  ADMINISTRATOR = 'ADMINISTRATOR',
}

export enum SpecimenStatus {
  RECEIVED = 'RECEIVED',
  LABELED = 'LABELED',
  ASSIGNED = 'ASSIGNED',
  IN_QUEUE = 'IN_QUEUE',
  PROCESSING = 'PROCESSING',
  REJECTED = 'REJECTED',
}

export enum ResultStatus {
  PENDING_CONFIRM = 'PENDING_CONFIRM',
  PENDING_SUPERVISOR_APPROVAL = 'PENDING_SUPERVISOR_APPROVAL',
  APPROVED = 'APPROVED',
  RELEASED = 'RELEASED',
  RETURNED_FOR_CORRECTION = 'RETURNED_FOR_CORRECTION',
  CRITICAL_ESCALATED = 'CRITICAL_ESCALATED',
}

export enum RejectionReason {
  INSUFFICIENT_VOLUME = 'INSUFFICIENT_VOLUME',
  WRONG_CONTAINER = 'WRONG_CONTAINER',
  UNLABELED = 'UNLABELED',
  OTHER = 'OTHER',
}

export enum ProbabilityLevel {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
}

export enum AssignmentStatus {
  ACTIVE = 'ACTIVE',
  RETURNED = 'RETURNED',
  COMPLETED = 'COMPLETED',
}

export enum PendingSyncAction {
  REJECT_SPECIMEN = 'REJECT_SPECIMEN',
  CONFIRM_RESULT = 'CONFIRM_RESULT',
  OVERRIDE_PARAMETER = 'OVERRIDE_PARAMETER',
  DISCARD_IMAGE = 'DISCARD_IMAGE',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
}

export enum PendingSyncStatus {
  PENDING = 'PENDING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
}
